# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebfec2813f6bb4dc813ed4ab3ee27e86203573e66aab2249ea7bf86554c6a61cab5039f7fdac371c262a51c5cdbc972744abf64746ca29bd08b1495f6735acb7

test:
  secret_key_base: 4cf1ec723a27f74f02e6acbb9def704b35300164d2209e6be60ebeda6ff937462fb3c8b76eb88303f385f1117c697de26da8347b28a0daf18dcfd72890f7c1a7

# Do not keep production secreZts in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
